### ISSUE TITLE
Flash dump size

### ISSUE THREAD

**Issue by thomashondema** [basilfx/TRADFRI-Hacking#19]
In the readme the following is written regarding flash dump size:
> To dump the flash contents, use the command below (0x4000 is 256 KiB):
> `savebin output.bin 0x0 0x4000`

But when I run this I end up with a ~16KB file.
Shouldn't the filesize either be 0x40000 or 0x3E800?

**Comment by basilfx** [comment]
Thanks for reporting. I've fixed this.
