### ISSUE TITLE
Status of wireless peripheral support?

### ISSUE THREAD

**Issue by gnbl** [basilfx/TRADFRI-Hacking#32]
Is there any information about the support of the wireless functions (Zigbee for Tradfri, but BLE and others seem to be supported by EFR32MG1 as well) by your efforts (https://github.com/RIOT-OS/RIOT/blob/master/boards/ikea-tradfri/doc.txt) or the RIOT project in general?

<hr>
Maybe you could add some info to https://github.com/basilfx/TRADFRI-Hacking#custom-firmware (toolchain, debugger hardware, SDKs etc)?

**Comment by basilfx** [comment]
There is some work done on the radio driver for the EFR32 for RIOT-OS: https://github.com/RIOT-OS/RIOT/pull/9212. It's based on RAILlib, that I presume is also used for the original firmware.

**Comment by gnbl** [comment]
Thanks. That effort appears to have "died", so effectively there is no Tradfri radio support for RIOT and the hardware can only be used with the ARM MCU core.

**Comment by kaibeckmann** [comment]
> Thanks. That effort appears to have "died", so effectively there is no Tradfri radio support for RIOT and the hardware can only be used with the ARM MCU core.

It's not completely dead. If you want to try it, I can rebase it to the current RIOT version. But be aware, there is one very annoying and persistent bug with the 6LoWPAN fragmentation... 

We also have a "version" for the NimBLE support of RIOT in a private repo, but currently no resources to bring it upstream to RIOT.

**Comment by gnbl** [comment]
Thanks for the offer, but no need - unless there's an easy-to-use toolchain or a project to reuse the tradfri remotes as BLE controllers (Simplicity Studio code examples or generator), this is currently too involved for me.
I think this project's readme should point out that the hacking is somewhat limited.
