### ISSUE TITLE
[REUQEST] Also hosting ZNet EZSP NCP Zigbee coordinator firmware for ICC-A-1

### ISSUE THREAD

**Issue by Hedda** [basilfx/TRADFRI-Hacking#35]
@basilfx FYI @mtx512 now also build custom ZNet EZSP NCP Zigbee coordinator firmware for ICC-A-1

- https://github.com/mtx512/efr32
  - https://github.com/mtx512/efr32/tree/master/icc-a-1

@MattWestb has posted documentation on how-to flash that firmware on ICC-A-1

- https://github.com/MattWestb/IKEA-TRADFRI-ICC-A-1-Modul

**Comment by basilfx** [comment]
I added this to the README.md: https://github.com/basilfx/TRADFRI-Hacking#ezsp
