### ISSUE TITLE
Dev board

### ISSUE THREAD

**Issue by arcidodo** [basilfx/TRADFRI-Hacking#37]
Hi,

Can I order an dev board? Or do you know an good shop
To create one? I live in the Netherlands. 

Greeting Arco

**Comment by basilfx** [comment]
There are many PCB services that can print a board for you. It can be as simple as uploading the Kicad files. My favorite PCB service is Aisler.net ([project link](https://aisler.net/p/EZPFEBPX)).

Do note that the current development board is not perfect. You might want to consider #18 by @oliv3r.

**Comment by arcidodo** [comment]
thx

**Comment by oliv3r** [comment]
@basilfx omg welcome back :D yeah I do have to do a small fix on the devboard, that i'm planning on doing ... but time :(
