### ISSUE TITLE
New module in the GU10 RGB

### ISSUE THREAD

**Issue by CableCatDK** [basilfx/TRADFRI-Hacking#39]
IKEA product number: 804.392.28 (unrelased)
![IMG_2642](https://user-images.githubusercontent.com/13363063/102191941-62f51480-3eba-11eb-9861-aa225b8db420.jpg)
![IMG_2638](https://user-images.githubusercontent.com/13363063/102192045-85872d80-3eba-11eb-89f6-f3bdf56d5d1f.jpg)

**Comment by CableCatDK** [comment]
Text on RF shield:
MGM210L022INF2
Model: MGM210L22F
1934A01HB2

https://fccid.io/QOQMGM210L/User-Manual/User-Manual-4211003

![image](https://user-images.githubusercontent.com/13363063/102262044-d591de80-3f12-11eb-9c65-0739ac113fb0.png)

![image](https://user-images.githubusercontent.com/13363063/102262107-e7738180-3f12-11eb-9704-db825ad7609d.png)

**Comment by CableCatDK** [comment]
The module can be bought here: https://dk.farnell.com/silicon-labs/mgm210la22jnf2/lighting-module-2mbps-3-8v/dp/3249880
Data Sheet: http://www.farnell.com/datasheets/2865974.pdf
![image](https://user-images.githubusercontent.com/13363063/102264106-771a2f80-3f15-11eb-8c09-33ab1f68856e.png)
![image](https://user-images.githubusercontent.com/13363063/102264140-84cfb500-3f15-11eb-90ec-5d1b4f95bedd.png)

**Comment by basilfx** [comment]
Thanks for the heads-up. I have bought that light and torn it down. I'll add it to the repo.

**Comment by basilfx** [comment]
I have added some information about this module and the product It is in. Thanks!

**Comment by boelle** [comment]
@basilfx will check this, but did you add it as a kicad thing so we can use it without having to draw it up from scratch?
