### ISSUE TITLE
Memory sectors

### ISSUE THREAD

**Issue by Mes-ser** [basilfx/TRADFRI-Hacking#4]
I have question regarding memory sizes for bootloader / data / SimEEPROM - you wrote:
0x00000 - 0x03fff -> Bootloader + recovery image (16 KiB)
0x04000 - 0x????? -> Application data
0x????? - 0x3ffff -> Simulated EEPROM
And I looked on Datasheet for SimEEPROM and there was:
> For version 1, the EM35x and Mighty Gecko utilize either 4 kB or 8 kB of upper flash memory to store the simulated EEPROM
> For version 2, the simulated EEPROM requires 36 kB of upper flash storage

So depend on used version, we can assume correct memory addresses for different region <- But maybe i'm wrong?
it only takes to determine which version was used in this case -> it is possible to find used version?

I'm looking for that because I want to determine in which memory part Ikea placed model info etc.

**Comment by basilfx** [comment]
If I look at the list of C files used, it includes `sim-eeprom2-internal.c`. That would mean it is using the 36 KiB of memory for the simulated EEPROM.

If I look at [this image](https://github.com/basilfx/TRADFRI-Hacking/blob/master/firmwares/ikea/led1650r5-1.2.214.png), the last part isn't exactly 4 or 8 KiB.
