### ISSUE TITLE
Add a things section

### ISSUE THREAD

**Issue by kollokollo** [basilfx/TRADFRI-Hacking#40]
I have found some 3D printable objects beloging to the TRADFRI system. maybe one should add a new folder caused things to this repository. Or maybe just a file with a list of things and links to thingiverse or the like. 

Here are some already:

https://www.thingiverse.com/thing:2254364 Ikea TRÅDFRI (TRADFRI) remote UK light switch holder

https://www.thingiverse.com/thing:2195340 IKEA - Mandal - Tradfri remote holder + glass holder

https://www.thingiverse.com/thing:3254038 Foot IKEA Tradfri Detector

https://www.thingiverse.com/thing:3594356 Ikea Tradfri motion sensor shelter

**Comment by basilfx** [comment]
I want to have this repository focus more on the hardware side of the products. I don't think it's a bad idea, I just don't know how 3D printed parts would fit in this repository.

I'll close this issue for now.
