### ISSUE TITLE
Information on communication with and to the TRADFRI Gateway

### ISSUE THREAD

**Issue by kollokollo** [basilfx/TRADFRI-Hacking#41]
... can be found here: https://learn.pimoroni.com/tutorial/sandyj/controlling-ikea-tradfri-lights-from-your-pi

**Comment by kollokollo** [comment]
And here we have a good repository with all the programming details:

https://github.com/glenndehaan/ikea-tradfri-coap-docs

**Comment by basilfx** [comment]
I have added a link to this API documentation on the products page. Thanks.
