### ISSUE TITLE
Zigbee router firmware and project for IKEA Tradfri ICC-A-1 Modules

### ISSUE THREAD

**Issue by Hedda** [basilfx/TRADFRI-Hacking#43]
@basilfx What do you think about also providing or linking to Zigbee router firmware and project links in your repo?

Checkout Ikea Tradfri Zigbee Repeater Umbau project with Zigbee router firmware for IKEA Tradfri ICC-A-1 Modules:

https://forum.smartapfel.de/forum/thread/3820-ikea-tradfri-zigbee-repeater-umbau/

More discussion about IKEA Trådfri module based DIY routers here:

https://community.home-assistant.io/t/sonoff-zbbridge-sonoff-zigbee-bridge-from-itead/187346/88

That idea of that concept might beat the performance of these otherwise popular DIY CC2530/CC2531 based HA 1.2 routers:

https://www.zigbee2mqtt.io/how_tos/how_to_create_a_cc2530_router.html

Especially if use those EFR32MG21/ based IKEA Trådfri Modules that you found in newer IKEA Trådfri products with MGM210L

**Comment by basilfx** [comment]
I have added the link to the HASS page to the README. Thanks.
